name: HINATA

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install package
      run: |
        sudo apt-get -y install ffmpeg imagemagick wget git nodejs
        
    - name: Download File Bot
      run: |
        git clone https://github.com/AyGemuy/HINATA
        
    - name: Run File Bot
      run: |
        cd HINATA && npm install && npm update && node .
